### PR TITLE
Fixed random-connect and fastest-connect commands.

### PR DESCRIPTION
**Pull request by MitchellRandom**
Updated the Random and Fastest connect buttons to execute the correct protonvpn-cli command (-random-connect) as opposed to --random-connect.

Note: Could be an issue on my end where the --random-connect and --fastest-connect are unrecognised as commands.

### CODE REVIEW

**Comment by joelbduncan** [comment]
I don't think I'll merge this protonvpn-cli has updated there CLI tool to use:

protonvpn-cli -r, --random-connect | Connect to a random ProtonVPN server.
protonvpn-cli -f, --fastest-connect | Connect to the fastest available ProtonVPN server.

Could be worth updating your version of protonvpn-cli?

**Comment by MitchellRandom** [comment]
Just updated my protonvpn-cli. The options seem to mention the usage of --random-connect. Not quite sure why the command is not being identified.
image

**Comment by joelbduncan** [comment]
Ah that's interesting!

What distro are you using? Could be worth flagging the issue with protonvpn-cli

**Comment by MitchellRandom** [comment]
Picked it up from: https://raw.githubusercontent.com/ProtonVPN/protonvpn-cli/master/protonvpn-cli.sh as per their support page. Seems https://github.com/ProtonVPN/protonvpn-cli/blob/master/protonvpn-cli.sh allows --random, but not --random-connect, same goes for fastest connections.

Based on this, no need to merge as I am sure ProtonVPN have the intent of allowing --random-connect and --fastest-connect as valid options.

**Comment by joelbduncan** [comment]
Could be worth me using:
-d
-c
-f
-r

Would resolve this no matter that version of the client?

**Comment by MitchellRandom** [comment]
Based on what I have seen, I believe using the single letter options could allow for consistent functioning across the versions.

**Comment by joelbduncan** [comment]
Thanks a lot for your input.
Fixed in a869a61b80d3602065cd20f3785c8f825c48a947

**Pull request closed without merging**
